name: chat_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  after_layout: ^1.2.0
  animated_snack_bar: ^0.3.0
  animations: ^2.0.7
  audioplayers: ^3.0.0
  badges: ^3.0.2
  better_player: ^0.0.83
  byte_converter: ^1.3.0
  crypto: ^3.0.2
  cupertino_icons: ^1.0.2
  easy_image_viewer: ^1.2.0
  enum_to_string: ^2.0.1
  file_cache: ^0.2.0
  file_picker: ^5.2.5
  flutter:
    sdk: flutter
  flutter_chat_bubble: ^2.0.0
  flutter_secure_storage: ^7.0.1
  flutter_slidable: ^2.0.0
  flutter_video_info: ^1.3.1
  google_fonts: ^3.0.1
  image_picker: ^0.8.6
  loading_animation_widget: ^1.2.0+4
  mongo_dart: ^0.8.2
  ms_material_color: ^1.0.0
  open_filex: ^4.3.2
  path: ^1.8.2
  path_provider: ^2.0.12
  provider: ^6.0.5
  recase: ^4.1.0
  scrollable_positioned_list: ^0.3.5
  sticky_headers: ^0.3.0+2
  video_thumbnail: ^0.5.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
